openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: '/v1'
    description: Optional server description, e.g. Main (production) server

paths:
  /predict:
    post:
      operationId: controllers.predict_controller.predict
      summary: Returns a prediction
      description: predicion
      requestBody:
              required : True
              content:
                application/json :
                  schema:
                    type: object
                    properties:
                      id:
                        type: integer
      responses:
        '200':    # status code
          description: 'perfect' 
          content:
            application/json:
              schema: 
                type: object
                properties:
                  id:
                    type: integer
        '400':
          description: 'Bad request. User ID must be an integer and larger than 0.'
        '401':
          description: 'Authorization information is missing or invalid.'
        '404':
          description: 'A model with the specified name was not found.'
        '5XX':
          description: 'Unexpected error.'
          
                  
                  
            